# Generated by Django 5.0 on 2023-12-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
