# Generated by Django 5.0 on 2023-12-10 21:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_userpreferences'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userpreferences',
            unique_together={('user', 'preference')},
        ),
    ]
