# Generated by Django 5.0 on 2023-12-11 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_userpreferences_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinteraction',
            name='blocked',
        ),
    ]
