# Generated by Django 5.0 on 2023-12-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_remove_userinteraction_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinteraction',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
